### ISSUE TITLE
Can use Python download from python.org?

### ISSUE THREAD

**Issue by Js-GitHub** [doingmathwithpython/code#2]
I'm thinking of purchasing book.

Can I use Python downloade from python.org and sublime text 3 to perform all the exercises or do I have to use Anaconda and Jupyter?

**Comment by amitsaha** [comment]
You don't have to use Jupyter, but using Anaconda will make your life easier, especially if you are on Windows or Mac OS X. However, don't let that deter you, which operating system are you on? I will be happy to help you get setup if you don't want to use Anaconda.

In fact @Js-GitHub you don't need Jupyter at all, see: https://doingmathwithpython.github.io/trying-out-solutions.html for some instructions.

**Comment by SG-Github** [comment]
Thanks...
Sorry didn't respond earlier.

**Comment by amitsaha** [comment]
No problems, let me know if I can help.
